### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [stephj41/teacozy#5]
[Meets Expectations] Fantastic job!

**Great work with:**
- Easy to navigate project structure
- Descriptive comments
- Descriptive class/id names
- Relative link usage
- Descriptive commit messages
- Class/Id usage
- Not repeating code
- Dividing content into divs
- Closely matching the spec 

**Improve:**
- Indentation
- Removing default stylings
- Making sure the locations do not overlap the contact/footer sections

**Future challenges:**
- Responsive design with Media Queries

**Comment by stephanieaj** [comment]
Thank you for the through review.  I will work on removing default styling.  Just learned how to do that in the next lesson.  I was having a hard time with the <h2>Locations</h2> staying put.
